apiVersion: batch/V1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: buybox
              agrs:
                - /bin/bash
                - -C
                - date;echo Hello from the kubernetses cluster
          restartPolicy: OnFailure