apiVerion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-cloud-logging
  namespace: kube-system
  labels:
    k8s-app: fluened-cloud-logging
spec:
  template:
    metadata:
      namespace: kube-system
      lablels:
        k8s-app: fluentd-cloud-logging
    spec:
      containers:
        - name: fluentd-cloud-logging
          image: gcr.io/aa1:17
          resources:
            limits:
              cpu: 100m
              memory: 200MI
          env:
            - name: fluentd_args
              value: -q
          volumeMounts:
            - name: varlog
              mountPath: /var/log
              readonly: false
            - name: containers
              mountPath: /var/lib/docker/containers
              readOnly: false
      volumes:
        - name: containers
          hostPath:
            path: /var/lib/docker/containers
        - name: varlog
          hostPath:
            path: /var/log