apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      container:
        - name: nginx
          images: nginx:1.7.9
          ports:
            - containersPort: 80
kubectl create -f rc.yaml
kubectl get deploments